### ISSUE TITLE
JLCPCB order denied

### ISSUE THREAD

**Issue by Addy771** [electroniceel/protoboard#2]
Hello and thanks for the excellent protoboard designs. I tried to order the "protoboard-6x4-breakout" from JLCPCB, but the order was denied: 
![order cancelled](https://user-images.githubusercontent.com/11689983/34788664-24064cb4-f5f0-11e7-9c71-a3b07188f806.png)

Were you able to order this through JLCPCB before?

**Comment by electroniceel** [comment]
I just checked and I did order this file just at Elecrow, while I ordered the other designs at JLCPCB.

From their message It seems like they can't make the small SC-70 breakouts. Elecrow was able to make them, but sometimes there were parts of the through hole plating hanging next to the hole. No big issue, a bit of sandpaper fixes it. 

Maybe JLCPCB has a special technique to make them with better quality, but that probably won't work with the small pcbs.

You can now either remove the SC-70 breakouts (in Kicad or a gerber editor) or order this design at another fab like Elecrow. I'll add a note to the readme.

**Comment by Addy771** [comment]
Thanks for the information. I'll just order the 5x3's instead. The breakouts aren't very necessary for me, but I do want to place the order at JLCPCB so I can get an idea of what their turnaround time really is.

**Comment by Addy771** [comment]
I am changing my order to the 5x3's, and JLCPCB has informed me that they won't do half-cut holes at all, so the other breakout boards won't work either.

**Comment by mpmarks** [comment]
I got the 5x3 and 6x4 proto boards fabricated by DirtyPCBs.com. No problems at all. I just uploaded the gerbers and they fabricated them without any issues. 10 5x3 boards and 10 6x4 boards cost ~$50 with shipping. They took about 3 weeks to arrive.

Thanks for the design work! I think the boards will be quite useful for several projects.

**Comment by Addy771** [comment]
Yeah, JLCPCB also made the 5x3 boards for me and they look great. I've already used one, but it took some experimenting to get it to work. Using 63/37 rosin core solder, I found that I had to turn the temperature way down to be able to make tracks with the solder. When the temperature is too high, the solder is nearly impossible to bridge between pads.

**Comment by andrewcchen** [comment]
My order for 5x3's at JLCPCB got denied

> Hi， there is only holes in the board and you select surface finish with HASL. The tin will connect together to cause the short circuit.Please select ENIG if you need to do the board,thanks~

Seeing the pictures here I don't think HASL is really a problem. Maybe they just didn't want to drill so many holes for $2.

**Comment by zigastegu** [comment]
What is your Pads to Mask Clearance? Was it set to 0.0mm?
![2018-08-14 22_46_03-window](https://user-images.githubusercontent.com/1379063/44122556-c8417d7e-a024-11e8-97a1-c3cb839c9cf6.png)

**Comment by andrewcchen** [comment]
I used the gerber files `protoboard-5x3.zip` from the repo, which I assume has been used successfully before?

**Comment by zigastegu** [comment]
@andrewcchen Yes, originally there is no solder mask between pads. I added it, to look like
![2018-08-14 23_03_16-window](https://user-images.githubusercontent.com/1379063/44123109-06e0268c-a027-11e8-87af-67401d61228b.png)
Will report if they accept/deny.

**Comment by zigastegu** [comment]
Their online viewer couldn't display gerbers. Had to wait. Design was approved.

**Comment by vatrat** [comment]
JLCPCB here.

> Hi Sir，
>
>Well got your order with many thanks！
>
>But really sorry to tell you that since after spraying tin, the pads will be linked together, so that it need to make it with ENIG instead HASL ,could you please kindly check?
>
>We have can celled your order and made the refund so that you can replace your order when you fix it, please kind check it, thanks~ 
![unnamed](https://user-images.githubusercontent.com/12566788/46520474-bcc11500-c841-11e8-9c06-d5fc9004bc80.png)

I'm not entirely certain, but it looks like the layers are messed up in the picture. I used the 5x3 gerber zip without modifications. 

I'll try the clearance modification.

@luftek I'm not familiar with PCB design, how did you add the solder mask in KiCad? When I look, I see that the pads to mask clearance is set to 0.2. I'd like to use the 5x3 setup.

**Comment by electroniceel** [comment]
I do not recommend to order these boards at JLCPCB anymore.
See https://github.com/electroniceel/protoboard#how-to-get

**Comment by mytja** [comment]
![aproved](https://user-images.githubusercontent.com/52399966/98545258-81ea0080-2295-11eb-9a8e-0cf7e1d27e3b.PNG)

Hmmm.
They approved it to me!

**Comment by electroniceel** [comment]
Thank you for the feedback.

I have made the experience that either the exact criteria for acceptance change from time to time, or, and I think that is more probable, it depends on which engineer was randomly assigned to checking your design. One is more relaxed and the other one more strict. So if not accepted, do a very small change (I think they do checksum matching of existing designs) and try again a few days later...
