### ISSUE TITLE
ESP32?

### ISSUE THREAD

**Issue by sixtyfive** [electroniceel/protoboard#6]
Thinking of ordering a bunch of protoboards to keep around because they seem to be generally useful, but also I have one concrete use, which would include an esp-wroom-32 (2mm raster!). Has anyone ever used a similar package on that protoboard layout?

![image](https://user-images.githubusercontent.com/192860/61946081-ebaba180-afa1-11e9-8f6a-293f4bf919b9.png)

(Source: https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf)

One thing people do is this, which would obviously work. Just wondering if there is any concrete example for this layout, especially one that would use less vertical space than the below method.

![image](https://user-images.githubusercontent.com/192860/61946279-670d5300-afa2-11e9-9f8e-7dd0c4909b70.png)

(Source: https://www.esp8266.com/viewtopic.php?f=13&t=782)

**Comment by electroniceel** [comment]
The 2mm raster won't work well with my protoboard design. You'd have to lift the esp32-board to prevent shorts and use wires like in your picture. 

Also you have to keep the space below the pcb antenna free, even unpopulated protoboard-pads will affect the antenna.

So maybe a dip adapter exactly as shown in your photo is the best solution. Plugging the 2.54mm raster pin headers into the protoboard is no problem.

**Comment by sixtyfive** [comment]
All good considerations, thank you! Regarding the antenna thing, I completely hadn't thought about that. Perhaps best to scrape off the protoboard-pads below that. It's for a prototype anyways, so perhaps we'll just make the enclosure a little larger.
